Description: Pattern with packages for mako configurations
Name: jolla-configuration-mako
Requires:
- pattern:jolla-hw-adaptation-mako
- pattern:jolla-sailfish-applications
- pattern:jolla-ui-wayland
- pattern:jolla-sailfish-cellular-apps
# Early stages of porting benefit from these:
- pattern:sailfish-porter-tools

- sailfish-content-graphics-z@ICON_RES@

# For multi-SIM devices. Not mako.
#- jolla-settings-networking-multisim

# Introduced starting Sailfish OS 2.0.4.x:
# 3rd party accounts like Twitter, VK, cloud services, etc
- jolla-settings-accounts-extensions-3rd-party-all

# For Mozilla location services (online)
- geoclue-provider-mlsdb

# Sailfish OS CSD tool for hardware testing
# needs some configuration to get all features working
- csd

Summary: Jolla Configuration mako

